# Create mapping from server "environment" (development|test|production) to database

development:
  adapter: postgresql
  database: development
  host: localhost
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
test:
  adapter: postgresql
  database: test
  host: localhost
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>